config/routes.rb
Rails.application.routes.draw do

  resources :breweries do
    resources :beers, except: [:index, :show]
  end

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  belongs_to :brewery
end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  has_many :beers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController

  respond_to :html

  def index
    @breweries = Brewery.all
  end

  def new
  end

  def create
    @brewery = Brewery.new(brewery_params)
    respond_with @brewery do |format|
      if @brewery.save
        flash[:notice] = "Brewery Created"
        format.html { redirect_to @brewery }
      # else
      # flash[:notice] = "Invalid Entry"
      # format.html { render :new }
      end
    end
  end

  def show
    @brewery = Brewery.find(params[:id])
    @beers = @brewery.beers
  end

  def edit
    @brewery = Brewery.find(params[:id])
  end

  def update
    @brewery = Brewery.find(params[:id])
    @brewery.update(brewery_params)
    redirect_to @brewery
  end

  def destroy
    @brewery = Brewery.find(params[:id])
    @brewery.destroy
    redirect_to breweries_path
  end

  private

  def brewery_params
    params.require(:brewery).permit(:name, :location)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/index.html.erb
<table>
  <thead>
    <th>Name</th>
    <th>Location</th>
  </thead>
  <% @breweries.each do |brewery| %>
  <tbody>
    <td><%= link_to brewery.name, brewery_path(brewery) %></td>
    <td><%= brewery.location %></td>
  </tbody>
  <%end%>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RspecBeer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>